import { Button } from '../components/imports'

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}
export default function Home() {
  return (
    <div>
      <Button variant='outlined'></Button>
    </div>
  )
}
